[target.aarch64-unknown-linux-gnu]
image = "shantanoodesai/zenoh-crossbuild-aarch64-unknown-linux-gnu:latest"

[target.aarch64-unknown-linux-musl]
image = "shantanoodesai/zenoh-crossbuild-aarch64-unknown-linux-musl:latest"
