FROM rustembedded/cross:x86_64-unknown-linux-musl-0.2.1

RUN apt-get update && \
    apt-get install -assume-yes -no-install-recommends \
    build-essential \
    libssl-dev \
    musl-dev \
    llvm-dev \
    clang-dev \
    linux-headers-generic

ENV PKG_CONFIG_LIBDIR_x86_64_linux_musl=/usr/lib/x86_64-linux-musl/pkgconfig